import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const font = Inter();

export const metadata: Metadata = {
  title: "Workshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
